# Generated by Django 4.1.7 on 2023-02-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perso", "0002_alter_perso_image_alter_photo_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perso",
            name="image",
            field=models.ImageField(default="", upload_to="perso/images"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(default="", upload_to="evidence/images"),
        ),
    ]
