# Generated by Django 4.1.7 on 2023-02-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perso", "0004_perso_user_guiltylist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Secret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="perso",
            name="secrets",
            field=models.ManyToManyField(related_name="secrets", to="perso.secret"),
        ),
    ]
