# Generated by Django 4.1.7 on 2023-02-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perso", "0005_secret_perso_secrets"),
    ]

    operations = [
        migrations.AddField(
            model_name="perso",
            name="known_secrets",
            field=models.ManyToManyField(
                related_name="known_secrets", to="perso.secret"
            ),
        ),
    ]
