# Generated by Django 4.1.7 on 2023-02-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perso", "0006_perso_known_secrets"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnownSecrets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="perso",
            name="known_secrets",
            field=models.ManyToManyField(
                related_name="known_secrets", to="perso.knownsecrets"
            ),
        ),
    ]
