# Generated by Django 4.1.7 on 2023-02-22 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("perso", "0010_alter_knownsecrets_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Relation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                (
                    "perso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="perso.perso"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="perso",
            name="relations",
            field=models.ManyToManyField(related_name="relations", to="perso.relation"),
        ),
    ]
