# Generated by Django 4.1.7 on 2023-02-22 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("perso", "0012_secret_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaveDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "secrets",
                    models.ManyToManyField(
                        related_name="save_secrets", to="perso.secret"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="perso",
            name="saveDocument",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saveDocument",
                to="perso.savedocument",
            ),
        ),
    ]
