# Generated by Django 4.1.7 on 2023-02-22 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("perso", "0013_savedocument_perso_savedocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedocument",
            name="secrets",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="save_secrets", to="perso.secret"
            ),
        ),
        migrations.CreateModel(
            name="AskTalkPerso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "join_perso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_perso",
                        to="perso.perso",
                    ),
                ),
                (
                    "perso_ask",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perso_ask",
                        to="perso.perso",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
