# Generated by Django 4.1.7 on 2023-02-22 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("perso", "0014_alter_savedocument_secrets_asktalkperso"),
    ]

    operations = [
        migrations.AddField(
            model_name="asktalkperso",
            name="perso",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="perso.perso"
            ),
            preserve_default=False,
        ),
    ]
