# Generated by Django 4.1.7 on 2023-02-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perso", "0020_alter_savedocument_secrets_sandby_notifytalk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perso",
            name="evidence",
        ),
        migrations.AddField(
            model_name="perso",
            name="slug_name",
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name="Evidence",
        ),
        migrations.DeleteModel(
            name="Photo",
        ),
    ]
