# Generated by Django 4.1.7 on 2023-02-24 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("perso", "0021_remove_perso_evidence_perso_slug_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifytalk",
            name="message",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name="HistoryAskTalkPerso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "join_perso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_join_perso",
                        to="perso.perso",
                    ),
                ),
                (
                    "perso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="perso.perso"
                    ),
                ),
                (
                    "perso_ask",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_perso_ask",
                        to="perso.perso",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
