# Generated by Django 4.1.7 on 2023-02-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perso", "0022_notifytalk_message_historyasktalkperso"),
    ]

    operations = [
        migrations.AddField(
            model_name="perso",
            name="description_breve",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
