# Generated by Django 4.1.7 on 2023-02-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perso", "0024_remove_sandby_asktalkperso_alter_perso_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perso",
            name="known_secrets",
            field=models.ManyToManyField(
                blank=True, related_name="known_secrets", to="perso.knownsecrets"
            ),
        ),
        migrations.AlterField(
            model_name="perso",
            name="relations",
            field=models.ManyToManyField(
                blank=True, related_name="relations", to="perso.relation"
            ),
        ),
        migrations.AlterField(
            model_name="perso",
            name="secrets",
            field=models.ManyToManyField(
                blank=True, related_name="secrets", to="perso.secret"
            ),
        ),
    ]
