# Generated by Django 4.1.7 on 2023-02-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perso", "0028_alter_knownsecrets_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relation",
            name="description",
            field=models.CharField(max_length=3000),
        ),
    ]
